//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreFrontEnd.WebStoreService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOProductsResponse", Namespace="http://schemas.datacontract.org/2004/07/WebStore.Entities.WCF.Products")]
    [System.SerializableAttribute()]
    public partial class DTOProductsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebStoreFrontEnd.WebStoreService.DTOProductsBody[] BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebStoreFrontEnd.WebStoreService.DTOResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebStoreFrontEnd.WebStoreService.DTOProductsBody[] Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebStoreFrontEnd.WebStoreService.DTOResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOResult", Namespace="http://schemas.datacontract.org/2004/07/WebStore.Entities.WCF")]
    [System.SerializableAttribute()]
    public partial class DTOResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebStoreFrontEnd.WebStoreService.EnumsResponseCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebStoreFrontEnd.WebStoreService.EnumsResponseCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Messaje {
            get {
                return this.MessajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessajeField, value) != true)) {
                    this.MessajeField = value;
                    this.RaisePropertyChanged("Messaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackError {
            get {
                return this.StackErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.StackErrorField, value) != true)) {
                    this.StackErrorField = value;
                    this.RaisePropertyChanged("StackError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOProductsBody", Namespace="http://schemas.datacontract.org/2004/07/WebStore.Entities.WCF.Products")]
    [System.SerializableAttribute()]
    public partial class DTOProductsBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.ResponseCode", Namespace="http://schemas.datacontract.org/2004/07/WebStore.Entities")]
    public enum EnumsResponseCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadRequest = 400,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unauthorized = 401,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 404,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidStatus = 406,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestTimeout = 408,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalServiceError = 500,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotImplemented = 501,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOPRoductsRequest", Namespace="http://schemas.datacontract.org/2004/07/WebStore.Entities.WCF.Products")]
    [System.SerializableAttribute()]
    public partial class DTOPRoductsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebStoreService.IWebStoreServices")]
    public interface IWebStoreServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebStoreServices/GetProducts", ReplyAction="http://tempuri.org/IWebStoreServices/GetProductsResponse")]
        WebStoreFrontEnd.WebStoreService.DTOProductsResponse GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebStoreServices/GetProducts", ReplyAction="http://tempuri.org/IWebStoreServices/GetProductsResponse")]
        System.Threading.Tasks.Task<WebStoreFrontEnd.WebStoreService.DTOProductsResponse> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebStoreServices/SetProducts", ReplyAction="http://tempuri.org/IWebStoreServices/SetProductsResponse")]
        WebStoreFrontEnd.WebStoreService.DTOProductsResponse SetProducts(WebStoreFrontEnd.WebStoreService.DTOPRoductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebStoreServices/SetProducts", ReplyAction="http://tempuri.org/IWebStoreServices/SetProductsResponse")]
        System.Threading.Tasks.Task<WebStoreFrontEnd.WebStoreService.DTOProductsResponse> SetProductsAsync(WebStoreFrontEnd.WebStoreService.DTOPRoductsRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebStoreServicesChannel : WebStoreFrontEnd.WebStoreService.IWebStoreServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebStoreServicesClient : System.ServiceModel.ClientBase<WebStoreFrontEnd.WebStoreService.IWebStoreServices>, WebStoreFrontEnd.WebStoreService.IWebStoreServices {
        
        public WebStoreServicesClient() {
        }
        
        public WebStoreServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebStoreServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebStoreServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebStoreServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebStoreFrontEnd.WebStoreService.DTOProductsResponse GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<WebStoreFrontEnd.WebStoreService.DTOProductsResponse> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public WebStoreFrontEnd.WebStoreService.DTOProductsResponse SetProducts(WebStoreFrontEnd.WebStoreService.DTOPRoductsRequest request) {
            return base.Channel.SetProducts(request);
        }
        
        public System.Threading.Tasks.Task<WebStoreFrontEnd.WebStoreService.DTOProductsResponse> SetProductsAsync(WebStoreFrontEnd.WebStoreService.DTOPRoductsRequest request) {
            return base.Channel.SetProductsAsync(request);
        }
    }
}
