USE [WebStore]
GO

/****** Object:  Table [dbo].[TB_Orders]    Script Date: 9/17/2017 1:02:27 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_Orders](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdUser] [int] NOT NULL,
	[TotalPriceOrdes] [nchar](10) NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TB_Orders]  WITH CHECK ADD  CONSTRAINT [FK_Table_1_TB_Customers] FOREIGN KEY([IdUser])
REFERENCES [dbo].[TB_Customers] ([Id])
GO

ALTER TABLE [dbo].[TB_Orders] CHECK CONSTRAINT [FK_Table_1_TB_Customers]
GO

